[project]
name = "in-the-loop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipython>=9.1.0",
    "openai>=1.71.0",
    "pydantic>=2.11.3",
]
